### ISSUE TITLE
This IP, site or mobile application is not authorized to use this API key. Request received from IP address 150.129.238.71, with empty referer

### ISSUE THREAD

**Issue by ravigupta9363** [seatgeek/android-PlacesAutocompleteTextView#10]
Android key not working

**Comment by ravigupta9363** [comment]
Must use server key

**Comment by sddamico** [comment]
@ravigupta9363 that's a great point about needing to use the server key and not the android key, I'll be sure to update the documentation, thank you!

**Comment by donUA** [comment]
Ensure to add both debug and release SHA 1 fingerPrints

**Comment by sharique112** [comment]
@ravigupta9363 can you please put some light on it, I didn't understood.

**Comment by donUA** [comment]
In the google cloud API console, there's a section where you can restrict the keys used to a specific platform. In case of android, you are required the application's  debug and release SHA 1 fingerPrints.

**Comment by sharique112** [comment]
I already have added that, but still getting same error "exception = {ApiException@16402} "com.google.android.gms.common.api.ApiException: 9011: This IP, site or mobile application is not authorized to use this API key. Request received from IP address 103.123.38.226, with empty referer" "
Getting this error when tried to use PlacesClient. For my api key i have enabled 
![image](https://user-images.githubusercontent.com/13073422/66470021-8185a180-eaa6-11e9-846a-eac51c795f3f.png)
the above apis. But still getting this error. Any leads will be helpful.

**Comment by vijaygoturi** [comment]
I am getting the below error after adding the selected APIs

flutter: {status: REQUEST_DENIED, errorMessage: You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started}

**Comment by GathuJames** [comment]
@vijaygoturi 
You have to provide you card details on the Google Cloud Console to be allowed to access the service

**Comment by CarSanoja** [comment]
Hello @sharique112 , did you solve that issue?

**Comment by gsgou** [comment]
Did you get it to work with Places API and an Android-App restricted key (package/SHA1) ?

**Comment by Yokesh1593** [comment]
Any update on this as i get same issue @sharique112
