### ISSUE TITLE
Support language different than english in PlaceDetails

### ISSUE THREAD

**Issue by re3lex** [seatgeek/android-PlacesAutocompleteTextView#16]
Hi,

getDetailsFor() method alway returning PlaceDetails in english because language parameter is not set in URL generated by PlacesApi.details() method.
This is an issue for non-english users.

I think best way is take to take system language as a base.

**Comment by re3lex** [comment]
Hi 

I have fixed this issue. Please check my pull request
https://github.com/seatgeek/android-PlacesAutocompleteTextView/pull/17

**Comment by riadhnet** [comment]
No resource identifier found for attribute 'pacv_languageCode' in package 'XXX'
did you added it in the last version ?

**Comment by re3lex** [comment]
what resource?

**Comment by riadhnet** [comment]
The version that i get from gradle doesn't have the latest version of code, it doesn't support languages , you didn't updated it with the pull request 17 ,
Can you please update it ?

**Comment by sddamico** [comment]
@riadhnet looks like our snapshot deploys are failing, sorry about that. I'll take a look when I get a chance.

**Comment by riadhnet** [comment]
@sddamico thanks, would you do this soon ? i'm using the library in my project , if it would take time i would rather move on for another alternative

**Comment by sddamico** [comment]
@riadhnet I'll try to get to this tomorrow.
