### ISSUE TITLE
How to search on specific country

### ISSUE THREAD

**Issue by Matevos** [seatgeek/android-PlacesAutocompleteTextView#24]
I want do search only in Germany i.e how could I set country so the result not be from another country?

**Comment by sddamico** [comment]
@Matevos the places API does not allow you to restrict results to a specific country, however you can pass a lat/lon and a radius for your search results, info [here](https://developers.google.com/places/web-service/autocomplete#location_biasing) and [here](https://github.com/seatgeek/android-PlacesAutocompleteTextView#location-biasing)

If you'd like to change the language of the results, you can do so using [`setLanguageCode()`](https://github.com/seatgeek/android-PlacesAutocompleteTextView/blob/master/placesautocomplete/src/main/java/com/seatgeek/placesautocomplete/PlacesAutocompleteTextView.java#L438).

Hope this helps.
