### ISSUE TITLE
Always return the same lat, long 

### ISSUE THREAD

**Issue by Felichejmz** [seatgeek/android-PlacesAutocompleteTextView#28]
always return lat=-1 and lng =-1

**Comment by sddamico** [comment]
Hey @Felichejmz, thanks for the issue report. Can you provide more details on the methods that you are calling to get the results you're seeing?

**Comment by HolySamosa** [comment]
I'm seeing the same issue when using getDetailsFor(place).  geometry.location lat & lng are -1.  I've confirmed via a web call with the same place ID that Google is returning an accurate location object.

**Comment by HolySamosa** [comment]
Looks like this is due to a bug in AndroidPlacesApiJsonParser.readGeometry().  Using the Gson implementation instead works around the issue.

**Comment by sddamico** [comment]
@HolySamosa pr's welcome :)

**Comment by nian88** [comment]
how to solve it?

**Comment by santoshthorani** [comment]
still getting same lat lng for all places.

**Comment by HolySamosa** [comment]
@nian88 Sorry this is crazy late, but maybe it will help someone.  You can work around the bug causing the -1, -1 lat / long simply by including GSON as a dependency:

    compile 'com.google.code.gson:gson:2.3.1'

GSON will then be used for parsing rather then the internal JSON processor.

**Comment by mickychen0524** [comment]
@sddamico @HolySamosa is this fixed? I am getting same result

**Comment by mickychen0524** [comment]
@HolySamosa it works!
