### ISSUE TITLE
Set text color of suggestions?

### ISSUE THREAD

**Issue by HolySamosa** [seatgeek/android-PlacesAutocompleteTextView#29]
I'm having trouble with styling the popup window.  My application has a dark theme and the color of the suggestion text is nearly white on the nearly white background.  My efforts to change the text color to something legible have thus far been unfruitful.  Assistance would be most appreciated!

**Comment by sddamico** [comment]
@HolySamosa My best advice would be to use a custom adapter for the list. An example of how to do that is in the test app [here](https://github.com/seatgeek/android-PlacesAutocompleteTextView/blob/master/demo-app/src/main/res/layout/activity_places_autocomplete.xml#L20)

**Comment by HolySamosa** [comment]
Thanks, this did the trick!
