### ISSUE TITLE
can not get latitude and longitude from the PlacesAutocompleteTextView

### ISSUE THREAD

**Issue by sultan-arshi** [seatgeek/android-PlacesAutocompleteTextView#30]
PlacesAutocompleteTextView etFromLocatin;
etFromLocatin = (PlacesAutocompleteTextView) view.findViewById(R.id.etFrom);

etFromLocatin.setOnPlaceSelectedListener(new OnPlaceSelectedListener() {
            @Override
            public void onPlaceSelected(@NonNull com.seatgeek.placesautocomplete.model.Place place) {     
            }
        });
can not get latitude and longitude Please fix it

**Comment by sddamico** [comment]
You can fetch more details (such as geolocation) about a place using the place details API.

Please see `PlacesAutocompleteTextView#getDetailsFor(Place, DetailsCallback)`
