### ISSUE TITLE
I try to find a way to insert a `Fragment` `Context` into the adapter

### ISSUE THREAD

**Issue by erikswed** [seatgeek/android-PlacesAutocompleteTextView#31]
Thanks all for the PlacesAutocompleteTextView it´s really helpful
I try to find a way to insert a `Fragment` `Context` into the adapter but ended up creating the  `setContext(.. `method as you can see down below. 
Any ide how to do this in a better way? 
in Fragment..
``` 
        mAutocomplete = (PlacesAutocompleteTextView) v.findViewById(R.id.autocomplete);
        mAutocomplete.setOnPlaceSelectedListener(this);
        ((TestPlacesAutocompleteAdapter)mAutocomplete.getAutocompleteAdapter()).setContext(this);
```
in AbstractPlacesAutocompleteAdapter 
```
public class TestPlacesAutocompleteAdapter extends AddressFilterAdapter {
    public TestPlacesAutocompleteAdapter(final Context context, final PlacesApi api, final AutocompleteResultType resultType, final AutocompleteHistoryManager history) {
        super(context, api, resultType, history);
    }
    @Override
    protected View newView(final ViewGroup parent) {
        return LayoutInflater.from(parent.getContext()).inflate(R.layout.places_autocomplete_item, parent, false);
    }

    @Override
    protected void bindView(final View view, final Place item) {
        ((TextView) view).setText(item.description);
    }
}
```

```

public abstract class AddressFilterAdapter extends AbstractPlacesAutocompleteAdapter implements
       , Runnable {
    public AddressFilterAdapter(final Context context,
                                final PlacesApi api,
                                final AutocompleteResultType resultType,
                                final AutocompleteHistoryManager history) {
        super(context, api, resultType, history);
        mRefreshLock = new Object();
        mHandler = new Handler();
        mRefreshRequested = false;
        mRefreshInProgess = false;
        mNextRefresh = new Date();
    }
    public void setContext(HomeFragment context){

        this.mWeakReference = new WeakReference<HomeFragment>(context);
    }
    @Override
    public void run() {
        onChange();
    }
}
```

**Comment by sddamico** [comment]
The parent adapter class (`ArrayAdapter`) already has a references to the current context which you can fetch with `getContext()`.

https://developer.android.com/reference/android/widget/ArrayAdapter.html#getContext()

There should be no need for a second reference to the Adapter's context.

**Comment by erikswed** [comment]
but the `Fragment `does not have a context and the `getContext()` returns `Fragment` parent context right? are you saying I should enter the `getContext().<parent(activity)>.FragmentManager `and search for the above "HomeFragment" reference?

**Comment by erikswed** [comment]
yea `FragmentManager ` is accessable and This works: 
        ```
final FragmentActivity activity = (FragmentActivity) ((FragmentActivity) **getContext()**).getParent();
        FragmentManager manager = activity.getSupportFragmentManager();
        Fragment frag = manager.findFragmentByTag("com.tarn.android.ui.HomeFragment");
        this.mWeakReference = new WeakReference<HomeFragment>((HomeFragment) frag);
```

**Comment by sddamico** [comment]
I guess I'm confused why the adapter needs a reference to the fragment?

**Comment by erikswed** [comment]
Im extending the `TestPlacesAutocompleteAdapter `with `AddressFilterAdapter` to do work on the returned `PlaceDetails`. This is experimental and I´m still learning doe. Since the `PlaceDetails` that i get from the `public void onPlaceSelected(@Non` will be processed heavily and there is a relation to the `ListView `row I figure I bake everything together like this.
