### ISSUE TITLE
Troubling styling to a dark themed dropdown

### ISSUE THREAD

**Issue by apMadden** [seatgeek/android-PlacesAutocompleteTextView#33]
Hey I am having trouble styling the dropdown to be a dark theme. This is what I get:

![darktheme](https://cloud.githubusercontent.com/assets/10348547/19735124/3c3cad92-9b78-11e6-8a2d-f9efe873f8fd.jpg)

My custom adapter looks like this:

    public class PlacesAutocompleteAdapter extends AbstractPlacesAutocompleteAdapter {
        public PlacesAutocompleteAdapter(final Context context, final PlacesApi api, final AutocompleteResultType autocompleteResultType, final AutocompleteHistoryManager history) {
            super(context, api, autocompleteResultType, history);
        }

        @Override
        protected View newView(final ViewGroup parent) {
            return LayoutInflater.from(parent.getContext()).inflate(R.layout.dark_list_item, parent, false);
        }

        @Override
        protected void bindView(final View view, final Place item) {
            ((TextView)view).setText(item.description);
        }
    }

The view is defined in my XML like this:

                <com.seatgeek.placesautocomplete.PlacesAutocompleteTextView
                    android:id="@+id/et_di_address_line_1"
                    style="@style/ClearableEditTextCheckout"
                    android:completionThreshold="2"
                    android:inputType="textPostalAddress|textCapWords|textNoSuggestions"
                    android:nextFocusDown="@+id/et_di_address_line_2"
                    android:text="@={deliveryViewModel.address1}"
                    app:pacv_adapterClass="com.my.app.PlacesAutocompleteAdapter"
                    app:pacv_googleMapsApiKey="@string/google_maps_key"/>

I have set the theme in my `styles.xml`:
        <item name="pacv_placesAutoCompleteTextViewStyle">@style/Widget.PlacesAutoCompleteTextView.Styled</item>

    <style name="Widget.PlacesAutoCompleteTextView.Styled"
           parent="PACV.Widget.PlacesAutoCompleteTextView">
        <item name="android:background">@color/suggested_card_dialog</item>
        <item name="android:textColor">@android:color/white</item>
    </style>

**Comment by sddamico** [comment]
PATV does not currently have a dark theme. If you want to change the style of the popup background, you'll want to copy the background drawable file [here](https://github.com/seatgeek/android-PlacesAutocompleteTextView/blob/master/placesautocomplete/src/main/res/drawable/pacv_popup_background_white.xml) and change the colors and switch to using the `pacv_powered_by_google_on_non_white` drawable for the google logo.

To set the background properly, you'll want to use `setDropDownBackgroundResource(Drawable)` on the PlacesAutocompleteTextView itself.

**Comment by apMadden** [comment]
Wow thanks for the super super quick response. Solution worked great thank you!

**Comment by sddamico** [comment]
No problem, glad it worked!
