### ISSUE TITLE
How to limit google autocomplete results to City and Country only

### ISSUE THREAD

**Issue by fmanoir** [seatgeek/android-PlacesAutocompleteTextView#35]
How to limit google autocomplete results to City and Country only

**Comment by spacewideweb** [comment]
Hi Did you get correct answer for your problem?
I am getting the problem like yours in my project.

**Comment by sddamico** [comment]
If you read the documentation for the places autocomplete api, there are ways to restrict results to a particular location and radius or, alternatively, to within a country:

https://developers.google.com/places/web-service/autocomplete

The [PlacesApi](https://github.com/seatgeek/android-PlacesAutocompleteTextView/blob/master/placesautocomplete/src/main/java/com/seatgeek/placesautocomplete/PlacesApi.java) implementation in this project implements parts of that, but you'd likely need to make some changes and submit a pr to add support.

**Comment by ajayqualwebs** [comment]
Thanks For Wonder enhancement in your work, it's also a great feature.

**Comment by sddamico** [comment]
Closed by https://github.com/seatgeek/android-PlacesAutocompleteTextView/pull/96

**Comment by hulisani-mudimeli** [comment]
Im currently using version: implementation 'com.seatgeek:placesautocomplete:0.3-SNAPSHOT'

However, which version contains the new country/city filter capability?
