### ISSUE TITLE
search for an address or a business?

### ISSUE THREAD

**Issue by qtmspin** [seatgeek/android-PlacesAutocompleteTextView#36]
Is it possible to request a list of matching address and businesses?  I've tried all 
pacv_resultType combos, and it seems I'm limited to either businesses or addresses.

**Comment by sddamico** [comment]
@qtmspin from the [api documentation](https://developers.google.com/places/web-service/autocomplete#place_types) it does seem that the places autocomplete api supports multiple  types in an array as a parameter. This feature isn't currently implemented by the library, we accept PR's! Otherwise, it might be a little bit before I get to it.

**Comment by qtmspin** [comment]
Thanks for the quick response, I noticed that the API mentions "If nothing is specified, all types are returned." is it possible to not specify a type?

**Comment by sddamico** [comment]
@qtmspin the code currently defaults to address if none are selected... https://github.com/seatgeek/android-PlacesAutocompleteTextView/blob/master/placesautocomplete/src/main/java/com/seatgeek/placesautocomplete/PlacesApi.java#L148

Would probably be a fairly simple change to revert setting the default.

**Comment by sddamico** [comment]
A better change would be adding a new option to the result types enum for "no type" and allowing users to specify that as a configuration option so that we don't upset the existing default result type

**Comment by qtmspin** [comment]
I've never submitted code to GH, but I will give it a shot

**Comment by sddamico** [comment]
Here's a quick overview of our guidelines for contributing that should help you get started! https://github.com/seatgeek/android-PlacesAutocompleteTextView#contributing

**Comment by qtmspin** [comment]
Here are the change.  I've tried several ways to commit the changes with no
luck

https://github.com/qtmspin/android-PlacesAutocompleteTextView-qtmspin
