### ISSUE TITLE
a request for dismissbutton

### ISSUE THREAD

**Issue by erikswed** [seatgeek/android-PlacesAutocompleteTextView#38]
Wonder if it would be hard to add this functionality to PlacesAutocompleteTextView like: 
Creating a clearable AutoCompleteTextView. (adding an ´x´ button to delete text content?

Here´s a tutorial doing this:
https://www.drzon.net/how-to-create-a-clearable-autocomplete-dropdown-with-autocompletetextview/

Some code from tutorial:
```
/**
 * sub class of {@link android.widget.AutoCompleteTextView} that includes a clear (dismiss / close) button with
 * a OnClearListener to handle the event of clicking the button
 * based on code from {@link http://www.gubed.net/clearableautocompletetextview}
 * @author Michael Derazon
 *
 */
public class ClearableAutoCompleteTextView extends AutoCompleteTextView {
	// was the text just cleared?
	boolean justCleared = false;

	// if not set otherwise, the default clear listener clears the text in the
	// text view
	private OnClearListener defaultClearListener = new OnClearListener() {

		@Override
```

**Comment by sddamico** [comment]
I think this is a worthy addition. A good implementation would have this be opt-in via a layout property, e.g. `patv_clearEnabled` or something to that effect.
