### ISSUE TITLE
	InputMethodManager leaks the last focused view

### ISSUE THREAD

**Issue by erikswed** [seatgeek/android-PlacesAutocompleteTextView#41]
I see this error using PlacesAutocompleteTextView.
https://gist.github.com/pyricau/4df64341cc978a7de414) 
Not sure if this is related to PlacesAutocompleteTextView!?

https://code.google.com/p/android/issues/detail?id=171190

Here´s a screenshot from leakcanary:
![screenshot_2017-02-24-18-37-37](https://cloud.githubusercontent.com/assets/3285249/23314070/9f1b7dc4-fac0-11e6-8171-a42df924cada.png)

**Comment by sddamico** [comment]
@erikswed without being able to see further up the tree to the gc root, it's impossible for me to say with certainty. I will say that since PlacesAutocompleteTextView is one away from the end, it is more likely that something is holding a reference to it than it holding a reference in a bad way.

**Comment by erikswed** [comment]
Thanks not sure what couches this, here´s a picture from Eclipse Memory Analyser and also I include the 
hprof file to debug this, if you have time and are good at this witch Im not. My `ActivityMain` when i rotate device 13 times get leakt 13 times 

**hprof file created by Android Studio Device monitor and converted using \Android\sdk\platform-tools>hprof-conv to work with Eclipse Memory Analyser** 
https://drive.google.com/file/d/0B3bM87DvaR5Pa0FKTi03MWtHbGc/view?usp=sharing

![eclikpsememoryanaylser1](https://cloud.githubusercontent.com/assets/3285249/23802704/63b26096-05b4-11e7-9dd8-c85be85451ca.png)

**Comment by sddamico** [comment]
Hey @erikswed, I took a look at your heap (sorry for the delay). It looks like you have a class called `ScrollingTextView` that is registering a runnable with the view root but is never removing callbacks. If that's the case you should be sure to check `isAttachedToWindow()` before re-registering for a callback with `post()` and `removeCallbacks()` in `onDetachedFromWindow()`

**Comment by erikswed** [comment]
my god your right and thanks for your time, it´s not easy being a beginner
at this thanks for your help

**Comment by sddamico** [comment]
No problem! feel free to reopen if you see an issue again.

For reference, when debugging a leak like this in MAT, be sure to look at the "Path to GC roots" as it will often lead to a chain of references that might have one of your classes in it!
