### ISSUE TITLE
In the OnPlaceSelectedListener I wonder how to get a hold of the Status Codes

### ISSUE THREAD

**Issue by erikswed** [seatgeek/android-PlacesAutocompleteTextView#43]
In the `OnPlaceSelectedListener` I wonder how to get a hold of the  [Status Codes](https://developers.google.com/places/web-service/search) I cannot see that it is propagated up to `public void onPlaceSelected(final Place place)`

The "status" field within the search response object contains the status of the request, and may contain debugging information to help you track down why the request failed. The "status" field may contain the following values:

**OK** indicates that no errors occurred; the place was successfully detected and at least one result was returned.
**ZERO_RESULTS** indicates that the search was successful but returned no results. This may occur if the search was passed a latlng in a remote location.
**OVER_QUERY_LIMIT** indicates that you are over your quota.
**REQUEST_DENIED** indicates that your request was denied, generally because of lack of an invalid key parameter.
**INVALID_REQUEST** generally indicates that a required query parameter (location or radius) is missing.

/Thanks

**Comment by sddamico** [comment]
@erikswed your best best for accessing more information from the network response will be to create your own instance of the `PlacesApi` where you can specify your own `PlacesHttpClient` which will allow you direct access to the response documents. The `onPlaceSelected()` and `placeDetails()` methods are more for the 95% common use case.
