### ISSUE TITLE
Autocomplete crashing in Play Store version of app

### ISSUE THREAD

**Issue by teekirol** [seatgeek/android-PlacesAutocompleteTextView#44]
The PlacesAutoCompleteTextView works perfectly fine when I'm running my app in Android Studio deployed to my USB device (using both release and debug build variants), but for some reason, when I deploy a Beta version and download it through the Play store, the app just stops when I start typing in an address.

My API key is using the Google Places API Web Service with no restrictions.

Any idea what's going on or how I can debug this?

**Comment by sddamico** [comment]
Hi @teekirol, is there any way that you can connect your Android device via USB and get the crash stacktrace from ADB?

Alternatively, if you're downloading from Google Play, you should be able to report the crash from your device and see the crash logs in the "Crashes and ANR's" section of the developer console.

**Comment by erikswed** [comment]
did you ad proguard-rules.pro:

# This rule will keep all seatgeek stuff
-keep class com.seatgeek.**{ *; }
-keep public interface
com.seatgeek.placesautocomplete.history.AutocompleteHistoryManager{*;}

**Comment by teekirol** [comment]
@sddamico Weirdly enough, there are no crash logs anywhere 🤔 

@erikswed That seemed to fix the problem -- thank you!
