### ISSUE TITLE
Several problem

### ISSUE THREAD

**Issue by SebastienGracia** [seatgeek/android-PlacesAutocompleteTextView#45]
The following classes could not be instantiated:
- com.seatgeek.placesautocomplete.PlacesAutocompleteTextView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details Write access not allowed during rendering (autocomplete)   at com.android.ide.common.rendering.RenderSecurityException.create(RenderSecurityException.java:52)   at java.io.File.mkdir(File.java:1311)   at java.io.File.mkdirs(File.java:1343)   at com.seatgeek.placesautocomplete.history.DefaultAutocompleteHistoryManager.fromPath   ... (DefaultAutocompleteHistoryManager.java:40)   at com.seatgeek.placesautocomplete.PlacesAutocompleteTextView.init(PlacesAutocompleteTextView.java:116)   at com.seatgeek.placesautocomplete.PlacesAutocompleteTextView.<init>(PlacesAutocompleteTextView.java:81)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard   

And another problem

Turn off custom view rendering sandbox  Diagnostic info for Studio bug report: Failed path: autocomplete Normal temp dir: C:\Users\hpProsg\AppData\Local\Temp\ Normalized temp dir: C:\Users\hpProsg\AppData\Local\Temp Canonical temp dir: C:\Users\hpProsg\AppData\Local\Temp os.name: Windows 10 os.version: 10.0 java.runtime.version: 1.8.0_112-release-b06Write access not allowed during rendering (autocomplete)   at com.android.ide.common.rendering.RenderSecurityException.create(RenderSecurityException.java:52)   at java.io.File.mkdir(File.java:1311)   at java.io.File.mkdirs(File.java:1343)   at com.seatgeek.placesautocomplete.history.DefaultAutocompleteHistoryManager.fromPath   ... (DefaultAutocompleteHistoryManager.java:40)   at com.seatgeek.placesautocomplete.PlacesAutocompleteTextView.init(PlacesAutocompleteTextView.java:116)   at com.seatgeek.placesautocomplete.PlacesAutocompleteTextView.<init>(PlacesAutocompleteTextView.java:81)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard   Tip: Try to refresh the layout.

**Comment by sddamico** [comment]
@SebastienGracia are you seeing this in the editor preview pane?

**Comment by sddamico** [comment]
Haven't heard response from user with issue, please repoen if seen again.
