### ISSUE TITLE
How to get latitude and logitude from place?

### ISSUE THREAD

**Issue by zeeshansardar61** [seatgeek/android-PlacesAutocompleteTextView#49]
I seen how you implement detailcallback to get city details but i want the exact latitude of the place we select.
```
 mAutocomplete.setOnPlaceSelectedListener(new OnPlaceSelectedListener() {
            @Override
public void onPlaceSelected(final Place place) {
       double lat = place.getLatitude();
       double lng = place.getLongitude();
});
```
Is there any way to get it that easily? If not then how? I am currently getting lat, lng via passing it in custom getAddress(String address). But want if any easy way available as I mentioned in my above code. 

Thanks in advance

**Comment by sddamico** [comment]
@zeeshansardar61 you should be able to use the `PlaceDetails` API to fetch the information that you're looking for!

```java
 mAutocomplete.setOnPlaceSelectedListener(new OnPlaceSelectedListener() {
            @Override
public void onPlaceSelected(final Place place) {
        mAutocomplete.getPlaceDetails(place, new PlaceDetailsCallback() {
           double lat = place.geometry.location.lat;
           double lng = place.geometry.location.lon;
});
```

**Comment by Anu07** [comment]
I am having trouble to call the same in kotlin. Please help

**Comment by sddamico** [comment]
@Anu07 accessing the fields on the place details should not be much different in kotlin, can you talk about what problem you're seeing in more depth?
