### ISSUE TITLE
add text before sent for search

### ISSUE THREAD

**Issue by Abbasd67** [seatgeek/android-PlacesAutocompleteTextView#55]
i wanted to add a text (e.g: city name like New York) when user input a text for search.
in short i want to restrict the search area for address but the location and radius method doesn't work for me. so i want to add the name of the city before sending for search address and get the results only for that city. like implement the adapter class for PlaceAutocompleteTextView and Override the textChange method before calling the super add the wanted text or something like it.
is there any way for it?

**Comment by sddamico** [comment]
I think your only other option would be overriding the `autocomplete()` method in `PlacesApi` and calling `setApi()` on the PATV
