### ISSUE TITLE
I am getting problem in add repository in Gradle file

### ISSUE THREAD

**Issue by ankurbhut** [seatgeek/android-PlacesAutocompleteTextView#56]
Faild to resolve : appcompate library : 26.0.0 
Faild to resolve : Support.design library : 26.0.0 
and also i can't install in project.

**Comment by sddamico** [comment]
@ankurbhut if you're already including support libraries in your own project, you can exclude the PATV's dependencies in gradle like this:

```
compile('com.seatgeek:placesautocomplete:0.3-SNAPSHOT'`) {
   exclude group: 'com.android.support'
}
```

**Comment by ankurbhut** [comment]
@sddamico  Thanks Buddy But still getting problem. Can you please send me the gradle file with added repository and dependency.

**Comment by ankurbhut** [comment]
Thanks @sddamico I have solved This error. But I got new error When I have run the program. This error message is paste below.
E/MapsPlacesAutoComplete: Unable to fetch autocomplete results from the api
                                                                             com.seatgeek.placesautocomplete.model.PlacesApiException: This IP, site or mobile application is not authorized to use this API key. Request received from IP address 0.00.000.00, with empty referer

**Comment by mf-mindcrewtech** [comment]
@ankurbhut how did you solve the error, can you plz let me know

**Comment by ankurbhut** [comment]
send your error.

**Comment by faisalvv** [comment]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.seatgeek:placesautocomplete:0.3-SNAPSHOT.
