### ISSUE TITLE
I have issue in runtime. I am not getting autoplace data in this. 

### ISSUE THREAD

**Issue by ankurbhut** [seatgeek/android-PlacesAutocompleteTextView#57]
I got error When I have run the program. This error message is paste below.

E/MapsPlacesAutoComplete: Unable to fetch autocomplete results from the api
com.seatgeek.placesautocomplete.model.PlacesApiException: This IP, site or mobile application is not authorized to use this API key. Request received from IP address 0.00.000.00, with empty referer

**Comment by sddamico** [comment]
@ankurbhut This does not appear to be an issue with this library, but instead an issue with your API key for Google APIs.

Please be sure you've followed the instractions in step one in the [setup instructions](https://github.com/seatgeek/android-PlacesAutocompleteTextView/blob/master/README.md#basic-setup-and-usage).
