### ISSUE TITLE
 Google Server API key

### ISSUE THREAD

**Issue by lexrrx** [seatgeek/android-PlacesAutocompleteTextView#58]
Hello in using a Server key the production app throws this exception: `This IP, site or mobile application is not authorized to use this API key. Request received from IP address` How can I solve this?

**Comment by sddamico** [comment]
@lexrrx when generating your API key in the Google API's console did you place restrictions on what IP addresses are whitelisted to use that key?

**Comment by lexrrx** [comment]
No, I did not place any restrictions. Even if I did let's say set restrictions how is that going to work within the context of the app?

**Comment by sddamico** [comment]
@lexrrx it would not work and it would show an error message probably similar to the one that you posted, hence why I asked.

Can you please verify that you've followed all the instructions shown here for getting your API key:

https://developers.google.com/places/web-service/get-api-key#if_you_are_using_the_standard_api_name_webservice_places

**Comment by lexrrx** [comment]
Yes I did follow exactly the procedure and the library works when in a debug mode but when I sign the apk I get the error. To my understanding, this is the expected behavior since I am using the code with an app and not a server. in this case, how do you get this working in a production environment?

**Comment by sddamico** [comment]
@lexrrx the "server" API key is just a name for the particular type of key that is not directly tied to a mobile package name, there is no restriction on its usage in a mobile app (google has no way of validating where an http request is coming from, be it a mobile device or a server). The "server" API key is the correct one to use in production (and it's the one that our app uses so I can verify that it does work).

Have you validated that you're using the same key in both your debug and release resources? (assuming you're providing it in XML).
