### ISSUE TITLE
setOnPlaceSelectedListener in Fragment

### ISSUE THREAD

**Issue by Sub-Zero-1** [seatgeek/android-PlacesAutocompleteTextView#60]
Hi!

Is there a way to get the setOnPlaceSelectedListener working in a fragment? I can implement a Button.OnClickListener in a Fragment, but I do not know how to do that with the setOnPlaceSelectedListener.

Thanks.

**Comment by erikswed** [comment]
In the Fragment xml layout, if you include the PlacesAutocompleteTextView you can reference it from the Fragment `onCreate()` just like i´m sure you did with the `Button`. Then attache the setOnPlaceSelectedListener like:

```
        mAutocomplete = rootView.findViewById(R.id.placesAutocompleteTextView);
        mAutocomplete.setOnPlaceSelectedListener(new OnPlaceSelectedListener() {
            @Override
            public void onPlaceSelected(@NonNull Place place) {
                
            }
        });
```
