### ISSUE TITLE
How I can get latitude & longitude after place selection ?

### ISSUE THREAD

**Issue by AmrutGhatage** [seatgeek/android-PlacesAutocompleteTextView#66]
autocomplete.setOnPlaceSelectedListener(
                new OnPlaceSelectedListener() {
                    @Override
                    public void onPlaceSelected(final Place place) {
                        // do something awesome with the selected place

                    }
                }
        );

**Comment by sddamico** [comment]
@AmrutGhatage once you have the `Place` object, you'll need to request the place details. Once you have the place details you should be able to access the lat/lon from the data model:

```
autocomplete.getDetailsFor(place, new DetailsCallback() {
                @Override
                public void onSuccess(PlaceDetails details) {
                    double lat = details.geometry.location.lat;
                    double lon = details.geometry.location.lon;
                }

                @Override
                public void onFailure(Throwable failure) {
                }

                public void onComplete() {
                }
            });
```
