### ISSUE TITLE
Why I only get 5 result in the demo app

### ISSUE THREAD

**Issue by TestDrive4** [seatgeek/android-PlacesAutocompleteTextView#67]
I went through the code and cannot find where this is set.
The drop down for any search result always give max 5 result. I check scroll more but nothing
Please advice?

**Comment by TestDrive4** [comment]
ok finally I found the text that explains this at:
https://developers.google.com/places/web-service/autocomplete#place_autocomplete_responses

" The Google Places API Web Service returns up to 5 results."

**Comment by sddamico** [comment]
@TestDrive4 I believe that this is a limitation of the ListPopupWindow that's used internally by AutocompleteTextView. There's an open issue to add scrolling to the inner container and show more results here:

https://github.com/seatgeek/android-PlacesAutocompleteTextView/issues/63
