### ISSUE TITLE
Does it makes sense to cashe the places api results locally

### ISSUE THREAD

**Issue by erikswed** [seatgeek/android-PlacesAutocompleteTextView#69]
Especially the `PlaceDetails` retrieved  from interface `PlacesApiJsonParser.detailsFromStream(..)` I was thinking since the data within `PlaceDetails` can be large considering.

Hade an ide to cache `PlaceDetails` since there is a unique `place_id`, somewhat just like history is persisted locally. 
Does it makes sense, i mean if the app is all about hammering Google places endpoint for much data.
Read somewhere Google allow for 30 days of local storage of the id´s data, but not sure!

    /**
     * Fetches the PlaceDetails for the given place_id. This is a
     * synchronous call, you must provide your own Async if you need it
     *
     * @param placeId the Google Maps Places API GooglePlace ID for the place you desire details of
     * @return the details for the place id
     * @throws IOException
     */
    public PlacesDetailsResponse details(final String placeId) throws IOException {
        Uri.Builder uriBuilder = Uri.parse(PLACES_API_BASE)
                .buildUpon()
                .appendPath(PATH_DETAILS)
                .appendPath(PATH_JSON)
                .appendQueryParameter(PARAMETER_KEY, googleApiKey)
                .appendQueryParameter(PARAMETER_PLACE_ID, placeId);

        if (languageCode != null) {
            uriBuilder.appendQueryParameter(PARAMETER_LANGUAGE, languageCode);
        }
        return httpClient.executeDetailsRequest(uriBuilder.build());
    }

**Comment by sddamico** [comment]
This seems like something that applications can do and it might be out of the scope of this library?
