### ISSUE TITLE
My google api key for the specific project does not work.

### ISSUE THREAD

**Issue by goutamkundu** [seatgeek/android-PlacesAutocompleteTextView#7]
While using the com.seatgeek.placesautocomplete.PlacesAutocompleteTextView got the exception while search for place 

Exception name com.seatgeek.placesautocomplete.model.PlacesApiException.
This IP, site or mobile application is not authorized to use this API key. Request received from IP address 122.169.212.109, with empty referer

**Comment by sddamico** [comment]
Please make sure that you've created an Android Key using the instructions outlined [here](https://developers.google.com/maps/documentation/android-api/signup#create_an_api_project_in_the_console_name). As part of that creation process, You'll need to ensure that you do not whitelist specific IP's for the key; mobile devices have constantly changing IP addresses.
