### ISSUE TITLE
Getting PlacesApiException 

### ISSUE THREAD

**Issue by Balakumarr7** [seatgeek/android-PlacesAutocompleteTextView#83]
Unable to fetch autocomplete results from the api
    com.seatgeek.placesautocomplete.model.PlacesApiException: This IP, site or mobile application is not authorized to use this API key. Request received from IP address.

I enabled Places API for android.

**Comment by MuthuSubramaniam** [comment]
Unable to fetch autocomplete results from the api
com.seatgeek.placesautocomplete.model.PlacesApiException: This IP, site or mobile application is not authorized to use this API key. Request received from IP address.

**Comment by sddamico** [comment]
When you created your API key with Google, did you whitelist a set of IP addresses that can use it? If so you'll probably want to reconsider that.

**Comment by MuthuSubramaniam** [comment]
Hi,

Yes it's working when I tried with place autocomolete text. But when I
tried using this library it's not working.
