### ISSUE TITLE
No Lat/Lng for some addresses

### ISSUE THREAD

**Issue by madcap66** [seatgeek/android-PlacesAutocompleteTextView#91]
I've added PlacesAutocompleteTextView to an app. It appears to be working corrrectly except certain addresses don't geocode the lat/lng. In a bid to check if it's the coding, I checked another app and the same address returns lat/lng.

I suspect that if a particular part of the address is not present, then it doesn't geocode??? For example, if the address doesn't have an 'suburb' of a 'city' then no geocode is present.

Can anyone confirm this?

**Comment by sddamico** [comment]
Are you able to proxy the responses from the google places api and see if the information is being returned in the api and it's just not parsing correctly or if the information is just being omitted?

**Comment by madcap66** [comment]
Hi and thanks for replying. I'm not quite sure what you mean by 'proxy the responses' but I instead used the new Google Places API and I get the correct lat/lng.

I am inclusing the code I used in case it throws any light on this:

`        mAutocomplete.setOnPlaceSelectedListener(
                new OnPlaceSelectedListener(){
                    @Override
                    public void onPlaceSelected(final Place place) {
                        // do something awesome with the selected place

                        mAutocomplete.getDetailsFor(place, new DetailsCallback() {
                            @Override
                            public void onSuccess(PlaceDetails details) {
                                // Create a new token for the autocomplete session. Pass this to FindAutocompletePredictionsRequest,
                                // and once again when the user makes a selection (for example when calling fetchPlace()).
                                AutocompleteSessionToken token = AutocompleteSessionToken.newInstance();
                                // Use the builder to create a FindAutocompletePredictionsRequest.
                                FindAutocompletePredictionsRequest request = FindAutocompletePredictionsRequest.builder()
                                        .setSessionToken(token)
                                        .setCountry(DEFAULT_LOCAL)
                                        .build();


                                Log.d("test", "details " + details);
                                double lat = details.geometry.location.lat;
                                double lng = details.geometry.location.lng;
                                mAutocomplete.setLocationBiasEnabled(Boolean.parseBoolean(DEFAULT_LOCAL));
                                mAutocomplete.setResultType(AutocompleteResultType.ADDRESS);
                                mEditTextAddressLine1.setText(details.name);

                                for (AddressComponent component : details.address_components) {
                                    for (AddressComponentType type : component.types) {
                                        switch (type) {
                                            case LOCALITY:
                                                editTextArea.setText(component.long_name);
                                                mEditTextLatitude.setText(String.valueOf(lat));
                                                mEditTextLongitude.setText(String.valueOf(lng));
                                                break;
                                            case ADMINISTRATIVE_AREA_LEVEL_1:
                                                break;
                                            case ADMINISTRATIVE_AREA_LEVEL_2:
                                                //TODO If adding in County
                                                break;
                                            case COUNTRY:
                                                editTextCountry2.setText(component.long_name);
                                                countrySpinner2.setSelection(dataAdapter.getPosition(component.long_name));
                                                break;
                                            case POSTAL_CODE:
                                                editTextPostcodeZip.setText(component.long_name);
                                                break;
                                            case POSTAL_TOWN:
                                                editTextCity.setText(component.long_name);
                                                break;
                                        }
                                    }
                                }

                            }

                            @Override
                            public void onFailure(final Throwable failure) {
                                Log.d("test", "failure " + failure);

                            }
                        });
                    }
                }


        );

        Task<FindAutocompletePredictionsResponse> task = placesClient.findAutocompletePredictions(requestBuilder.build());

        task.addOnSuccessListener(
                (response) ->
                        Toast.makeText(this, "Success", Toast.LENGTH_SHORT).show());

        task.addOnFailureListener(
                (exception) -> {
                    exception.printStackTrace();
                    Toast.makeText(this, "Exception", Toast.LENGTH_SHORT).show();
                });`

Thanks

**Comment by vpulpatil** [comment]
Same issue is happening with me as well. In my case, if I am searching specifically for **Ladakh**, place object is returning null.
