### ISSUE TITLE
¿Library updated?

### ISSUE THREAD

**Issue by peporroncin** [seatgeek/android-PlacesAutocompleteTextView#92]
Hi,

¿Is this library updated to last Google Places SDK?

https://developers.google.com/places/android-sdk/intro

_Deprecation notice: Google Play Services version of the Places SDK for Android
Notice: The Google Play Services version of the Places SDK for Android (in Google Play Services 16.0.0) is deprecated as of January 29, 2019, and will be turned off on July 29, 2019. A new version of the Places SDK for Android is now available. We recommend updating to the new version as soon as possible. For details, see the migration guide._

Thanks in advance.

**Comment by sddamico** [comment]
This library does not use the google play services places api and instead talks directly to Google's http api's.
