### ISSUE TITLE
MapsPlacesAutoComplete: Unable to fetch autocomplete results from the api

### ISSUE THREAD

**Issue by ITWhiz4U** [seatgeek/android-PlacesAutocompleteTextView#94]
It's not working on my app.

Now I'm getting this error.

MapsPlacesAutoComplete: Unable to fetch autocomplete results from the api
    java.net.SocketTimeoutException: connect timed out

Please check and let me know.
Best regards.

**Comment by sddamico** [comment]
Hey, @ITWhiz4U, sorry that you're seeing this error. A network timeout however doesn't sound like something that would be caused by this library, can you provide any additional information or logs regarding the issue you're seeing?
