### ISSUE TITLE
Failed to resolve: com.seatgeek:placesautocomplete:0.3-SNAPSHOT

### ISSUE THREAD

**Issue by rsaxenarishabh** [seatgeek/android-PlacesAutocompleteTextView#95]
when i am integrate your library in gradle file then i am getting this error.. so can you suggest me what is issue..
and i am using latest version of android studio

**Comment by sddamico** [comment]
@rsaxenarishabh can you confirm that you have the sonatype snapshots repository added to your `repositories` block in your build.gradle?

**Comment by rsaxenarishabh** [comment]
Thanks for your suggestion and now Api is working fine. so please could you tell me how i get location only in india..

**Comment by rsaxenarishabh** [comment]
Hii Team, 
I am facing one issue that i have created my google api key and set into this library then i have searching  location but result is not found.. could you help me?

Thanks
Rishabh
